FROM golang:1.27-alpine

# Instalar air compatible con Go 1.23+
RUN go install github.com/air-verse/air@v1.61.0

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]