name: teamcellmania-backend-dev

version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  kafka:
    image: apache/kafka:3.8.0
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"   # Para Legacy Express y herramientas locales
      - "9094:9094"   # Listener externo adicional
    environment:
      # KRaft obligatorio
      - KAFKA_NODE_ID
      - KAFKA_PROCESS_ROLES
      - KAFKA_CONTROLLER_QUORUM_VOTERS
      - KAFKA_CONTROLLER_LISTENER_NAMES

      # Listeners y Advertised (las más importantes)
      - KAFKA_LISTENERS
      - KAFKA_ADVERTISED_LISTENERS
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
      - KAFKA_INTER_BROKER_LISTENER_NAME

      # Configuraciones de desarrollo
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
      - KAFKA_LOG_RETENTION_HOURS
      - KAFKA_NUM_PARTITIONS
      - CLUSTER_ID
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - backend
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  gateway:
    build:
      context: ../gateway
      dockerfile: Dockerfile.dev
    container_name: ms-gateway
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ../gateway:/app
      - /app/node_modules
    command: ["npm", "run", "start"]
    environment:
      - NODE_ENV=development
      - INTERNAL_SECRET=${INTERNAL_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - RABBIT_URL=${RABBIT_URL}
    networks:
      - backend
    depends_on:
      rabbitmq:
        condition: service_healthy

  users:
    build:
      context: ../microservices/users
      dockerfile: Dockerfile.dev
    container_name: ms-users
    volumes:
      - ../microservices/users:/app
      - /app/node_modules
    restart: always
    command: ["npm", "run", "start"]
    environment:
      - NODE_ENV=development
      - INTERNAL_SECRET=${INTERNAL_SECRET}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME_USERS}
      - RABBIT_URL=${RABBIT_URL}
    networks:
      - backend
    depends_on:
      rabbitmq:
        condition: service_healthy

  orders:
    build:
      context: ../microservices/orders
      dockerfile: Dockerfile.dev
    container_name: ms-orders
    restart: always
    volumes:
      - ../microservices/orders:/app
      - /app/node_modules
    command: ["npm", "run", "start:dev"]
    environment:
      - NODE_ENV=development
      - INTERNAL_SECRET=${INTERNAL_SECRET}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME_ORDERS}
      - RABBIT_URL=${RABBIT_URL}
      - MYSQL_DB_HOST1=${MYSQL_DB_HOST1}
      - MYSQL_DB_USER=${MYSQL_DB_USER}
      - MYSQL_DB_PORT=${MYSQL_DB_PORT}
      - MYSQL_DB_PASSWORD=${MYSQL_DB_PASSWORD}
      - MYSQL_DB_NAME=${MYSQL_DB_NAME}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      # Descomenta cuando empieces con eventos de caja
      # - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - backend
    depends_on:
      rabbitmq:
        condition: service_healthy
      # kafka:
      #   condition: service_healthy   # ← activa cuando orders use Kafka

  clients:
    build:
      context: ../microservices/clients
      dockerfile: Dockerfile.dev
    container_name: ms-clients
    restart: always
    volumes:
      - ../microservices/clients:/app
      - /app/node_modules
    command: ["npm", "run", "start:dev"]
    environment:
      - NODE_ENV=development
      - INTERNAL_SECRET=${INTERNAL_SECRET}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME_CLIENTS}
      - RABBIT_URL=${RABBIT_URL}
      - KAFKA_BOOTSTRAP_SERVERS
    networks:
      - backend
    depends_on:
      rabbitmq:
        condition: service_healthy

  companies:
    build:
      context: ../microservices/companies
      dockerfile: Dockerfile.dev
    container_name: ms-companies
    restart: always
    volumes:
      - ../microservices/companies:/app
      - /app/node_modules
    command: ["npm", "run", "start"]
    environment:
      - NODE_ENV=development
      - INTERNAL_SECRET=${INTERNAL_SECRET}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME_COMPANIES}
      - RABBIT_URL=${RABBIT_URL}
    networks:
      - backend
    depends_on:
      rabbitmq:
        condition: service_healthy

  subscriptions:
    build:
      context: ../microservices/subscriptions
      dockerfile: Dockerfile.dev
    container_name: ms-subscriptions
    restart: always
    volumes:
      - ../microservices/subscriptions:/app
      - /app/node_modules
    command: ["npm", "run", "start"]
    environment:
      - NODE_ENV=development
      - INTERNAL_SECRET=${INTERNAL_SECRET}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME_SUBSCRIPTIONS}
      - RABBIT_URL=${RABBIT_URL}
    networks:
      - backend
    depends_on:
      rabbitmq:
        condition: service_healthy
  redis:
    image: redis:7-alpine
    container_name: redis-realtime
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  realtime:
    build:
      context: ../realtime
      dockerfile: Dockerfile.dev
    container_name: ms-realtime
    restart: always
    volumes:
      - ../realtime:/app
      - /app/node_modules
    command: ["npm", "run", "start:dev"]
    environment:
      - NODE_ENV=development
      - INTERNAL_SECRET=${INTERNAL_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - RABBIT_URL=${RABBIT_URL}
      - REDIS_URL=redis://redis:6379
    ports:
      - "3002:3002"          # ← expuesto directamente
    networks:
      - backend
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
networks:
  backend:

volumes:
  kafka_data:
  redis_data: