FROM node:20-alpine

WORKDIR /app

# Copiar archivos de configuración
COPY package*.json ./
COPY tsconfig*.json ./
COPY nest-cli.json ./

# Instalar dependencias
RUN npm ci --only=development

# Copiar código fuente (opcional, usa volumen)
COPY src ./src

EXPOSE 3010

CMD ["npm", "run", "start:dev"]
